image: archlinux
packages:
  - rustup
  - mesa
  - glu
  - libx11
  - glfw-x11
  - cmake
tasks:
  - prepare: |
      rustup toolchain install stable
      cd doppler/
      rustup run stable cargo fetch
  - build: |
      cd doppler/
      cargo build --release

