[package]
name = "doppler"
version = "0.1.0"
authors = ["Piotr <siuszko@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'
panic = 'abort'
lto = true

[dependencies]
cgmath = "0.17.0"
gl = "0.14.0"
image = "0.22.5"
imgui-glfw-rs = { git = "https://github.com/Leinnan/imgui-glfw-rs" }
imgui-inspect = "0.5.0"
imgui-inspect-derive = "0.5.0"
# only needed from chapter 3 on
tobj = "2.0.2"
num = "0.3.0"
rand = "0.7.3"
human-panic = "1.0.3"
inline_tweak = "1.0.8"
image2 = { git = "https://github.com/Leinnan/image2-rs", features = [] }
# serde = "1.0.116"
# serde_derive = "1.0.116"
# assets_manager ={ version="0.3.2", features= ["ron", "bincode"]}

[profile.dev.package."*"]
opt-level = 2