[package]
name = "doppler"
version = "0.1.0"
authors = ["Piotr <siuszko@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'
panic = 'abort'
lto = true

[dependencies]
cgmath = "0.17.0"
gl = "0.14.0"
glfw = "0.39.1"
image = "0.22.5"
# only needed from chapter 3 on
# tobj = "0.1.6"
# num = "0.2.0"
# rand = "0.5.5"
human-panic = "1.0.3"